apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: boutique
labels:
- pairs:
    app.kubernetes.io/part-of: online-boutique
resources:
- frontend.yaml
- adservice.yaml
- cartservice.yaml
- checkoutservice.yaml
- emailservice.yaml
- paymentservice.yaml
- productcatalogservice.yaml
- recommendationservice.yaml
- shippingservice.yaml
- currencyservice.yaml
- redis.yaml
- network-policies
images:
- name: 767397659229.dkr.ecr.us-east-1.amazonaws.com/online-boutique-eks/adservice
  newName: 767397659229.dkr.ecr.us-east-1.amazonaws.com/online-boutique-eks/adservice
  newTag: sha-cb4a3ca5b339854a850cc24f38048b17a2dea518
- name: 767397659229.dkr.ecr.us-east-1.amazonaws.com/online-boutique-eks/cartservice
  newName: 767397659229.dkr.ecr.us-east-1.amazonaws.com/online-boutique-eks/cartservice
  newTag: sha-cb4a3ca5b339854a850cc24f38048b17a2dea518
- name: 767397659229.dkr.ecr.us-east-1.amazonaws.com/online-boutique-eks/checkoutservice
  newName: 767397659229.dkr.ecr.us-east-1.amazonaws.com/online-boutique-eks/checkoutservice
  newTag: sha-cb4a3ca5b339854a850cc24f38048b17a2dea518
- name: 767397659229.dkr.ecr.us-east-1.amazonaws.com/online-boutique-eks/currencyservice
  newName: 767397659229.dkr.ecr.us-east-1.amazonaws.com/online-boutique-eks/currencyservice
  newTag: sha-cb4a3ca5b339854a850cc24f38048b17a2dea518
- name: 767397659229.dkr.ecr.us-east-1.amazonaws.com/online-boutique-eks/emailservice
  newName: 767397659229.dkr.ecr.us-east-1.amazonaws.com/online-boutique-eks/emailservice
  newTag: sha-cb4a3ca5b339854a850cc24f38048b17a2dea518
- name: 767397659229.dkr.ecr.us-east-1.amazonaws.com/online-boutique-eks/frontend
  newName: 767397659229.dkr.ecr.us-east-1.amazonaws.com/online-boutique-eks/frontend
  newTag: sha-cb4a3ca5b339854a850cc24f38048b17a2dea518
- name: 767397659229.dkr.ecr.us-east-1.amazonaws.com/online-boutique-eks/loadgenerator
  newName: 767397659229.dkr.ecr.us-east-1.amazonaws.com/online-boutique-eks/loadgenerator
  newTag: sha-cb4a3ca5b339854a850cc24f38048b17a2dea518
- name: 767397659229.dkr.ecr.us-east-1.amazonaws.com/online-boutique-eks/paymentservice
  newName: 767397659229.dkr.ecr.us-east-1.amazonaws.com/online-boutique-eks/paymentservice
  newTag: sha-cb4a3ca5b339854a850cc24f38048b17a2dea518
- name: 767397659229.dkr.ecr.us-east-1.amazonaws.com/online-boutique-eks/productcatalogservice
  newName: 767397659229.dkr.ecr.us-east-1.amazonaws.com/online-boutique-eks/productcatalogservice
  newTag: sha-cb4a3ca5b339854a850cc24f38048b17a2dea518
- name: 767397659229.dkr.ecr.us-east-1.amazonaws.com/online-boutique-eks/recommendationservice
  newName: 767397659229.dkr.ecr.us-east-1.amazonaws.com/online-boutique-eks/recommendationservice
  newTag: sha-cb4a3ca5b339854a850cc24f38048b17a2dea518
- name: 767397659229.dkr.ecr.us-east-1.amazonaws.com/online-boutique-eks/shippingservice
  newName: 767397659229.dkr.ecr.us-east-1.amazonaws.com/online-boutique-eks/shippingservice
  newTag: sha-cb4a3ca5b339854a850cc24f38048b17a2dea518
