---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: idpregcred
  namespace: kyverno
spec:
  encryptedData:
    .dockerconfigjson: AgBPRv6F4+CUtbIwqWcfJ+6bgtrrRbsTpCNrLKlkLoz1D7otNrupeBaQcwXkY2AYb/ZlVuvFTzZaOkgubmjMzzFrI+mEEEWE3BPRlWYV24ptLiXDhsfGRx2nkC056pONwoEh5oKhIP9w6O5Xs3HeSX8kkNZlfkGJjphxCANfnd11DxmiTE2D0cWpbrAZxZLKky2lX6y1S+FwXj45ZNrHzJCxwsNRJdrjoiximqimoy89cGG3pNOPRPkh7jKiLAPrkzsb8DKF1FWT4xZg9J59rylYTAEF2Md/xSb63RMg+5iRVCtmNUyDt6nMA4cR2vIixoP1qeHYUh4r85BnC4xbc/EoM1NUowV35rRbRNnOMNsqNvH6/Qiug1eLndlbDKaTbry3IBHizX/c7tDyd9HXDhUck7h5Y97HU+bnaQsE+U4WOBUh51lwVSi0uPIojLaDrvaUnJGgLdLXoxzRezw3nSbtLy+0S8aPJHlsdVVPPu19lJxGQrEvVs9o+fdBbe+NetxB3EbKGlsoEeSbV/xPdcBGrQHmJ5P3Om5v8D8y84rQvnUGgLZFeDmGLXx4bVhZ7im1VRLFFTIqLDGo7eltsKZ4LbNfpN7+k3YRzNO/vYTXaVihWlUOkFEa1vHpNCQ9qI/iSikL5E8oZ/kNdMu7KoLQyI0J06du5Go+ZfnPQBn2jBW7wcXswGG088YarOI8aokiqnyxh1a33s6YLpXMI24rLt1dQT5rXUIlI0GaJT5WLiLbgaDFC1JZb3IXkbh8uv9mzsuQCzRKTi9DJtEYO7cyjcVIYeCkOTQR3zrS9fsy0ceIecaCbzTYUpEtaxL97F5pivbuTkxEpi8MDwFKrxQEd7wrnp+dqdOVO8o7Wz5/kEe3R9SIgePfeN3eo3z9pwBKI9pPsImy61vOraHgTps1i9Jcy8gLegwrV0H0ERKjaSnD7rto574=
  template:
    metadata:
      name: idpregcred
      namespace: kyverno
    type: kubernetes.io/dockerconfigjson
