apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-image-signature
spec:
  validationFailureAction: Audit
  webhookTimeoutSeconds: 30
  rules:
    - name: verify-keyless-cosign
      match:
        any:
        - resources:
            kinds:
            - Pod
      verifyImages:
      - image: "registry.digitalocean.com/idpreg/*"
        mutateDigest: false
        key: |-
          -----BEGIN PUBLIC KEY-----
          MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEFser5E5Yw6U9xkMvxr7OG4wPhyaY
          qsk5srtZNDcf5REO2Zor/lmsynfPN6gZ72al9Z9DAssJzY5SSbUvburT5A==
          -----END PUBLIC KEY-----
        imagePullSecrets: 
          - name: docr-secret
        allowInsecureRegistry: false