
global:
  domain: argocd.suworks.me

configs:
  params:
    server.insecure: true
  cm:
    repositories: |
      - url: https://github.com/susu10-10/online-boutique-eks-pf
        type: git
        name: boutique-infra

server:
  replicas: 1
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-staging
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    tls: true
    hosts:
      - argocd.suworks.me
  metrics:
    enabled: true
    service:
      enabled: true
      servicePort: 8083

## Application controller
controller:
  # -- Application controller name string
  name: application-controller
  # -- The number of application controller pods to run.
  replicas: 1
  metrics:
    enabled: true
    service:
      enabled: true
      servicePort: 8082

## Repo Server
repoServer:
  # -- Repo server name
  name: repo-server
  # -- The number of repo server pods to run
  replicas: 1
  metrics:
    enabled: true
    service:
      enabled: true
      servicePort: 8084

## ApplicationSet controller
applicationSet:
  # -- ApplicationSet controller name string
  name: applicationset-controller
  # -- The number of ApplicationSet controller pods to run
  replicas: 1
  metrics:
    enabled: true
    service:
      enabled: true
      servicePort: 8080

## Redis
redis:
  # -- Enable redis
  enabled: true
  # -- Redis name
  name: redis