apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: platform-cluster-alerts
  namespace: prometheus
  labels:
    release: prometheus
spec:
  groups:
  - name: cluster.alerts
    rules:
    #
    # Node availability
    #
    - alert: NodeNotReady
      expr: |
        kube_node_status_condition{
          condition="Ready",
          status="true"
        } == 0

      for: 10m
      labels:
        severity: critical
      annotations:
        summary: "Kubernetes node is not ready"
        description: >
          Node {{ $labels.node }}
          has been NotReady for more than 10 minutes.


    #
    # Node memory pressure
    #
    - alert: NodeMemoryPressure
      expr: |
        kube_node_status_condition{
          condition="MemoryPressure",
          status="true"
        } == 1

      for: 5m

      labels:
        severity: warning
      annotations:
        summary: "Node memory pressure detected"
        description: >
          Node {{ $labels.node }}
          is experiencing memory pressure.



    #
    # Node disk pressure
    #
    - alert: NodeDiskPressure
      expr: |
        kube_node_status_condition{
          condition="DiskPressure",
          status="true"
        } == 1
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Node disk pressure detected"
        description: >
          Node {{ $labels.node }}
          is experiencing disk pressure.

    #
    # Kubernetes API unavailable
    #

    - alert: KubernetesAPIDown
      expr: |
        absent(up{job="apiserver"} == 1)
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "Kubernetes API server unavailable"
        description: >
          Prometheus cannot scrape Kubernetes API server.

    # High cluster cpu
    - alert: HighClusterCPU
      expr: |
        cluster:cpu_usage:percent > 80
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High cluster CPU usage detected"
        description: >
          Cluster CPU usage is above 80% for more than 5 minutes.

    # High Cluster Memory
    - alert: HighClusterMemory
      expr: |
        cluster:memory_usage:percent > 80
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High cluster memory usage detected"
        description: >
          Cluster memory usage is above 80% for more than 5 minutes.