apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule

metadata:
  name: gitops-recording-rules
  namespace: prometheus
  labels:
    release: prometheus

spec:
  groups:

  - name: gitops.recording.rules
    interval: 30s

    rules:


    #
    # Total ArgoCD Applications
    #
    - record: argocd:applications:total
      expr: |
        count(
          argocd_app_info
        )


    #
    # Synced Applications
    #
    - record: argocd:applications:synced
      expr: |
        count(
          argocd_app_info{
            sync_status="Synced"
          }
        )

    #
    # Applications unhealthy
    #
    - record: gitops:applications_unhealthy
      expr: |
        count(
          argocd_app_info{
            health_status!="Healthy"
          }
        )


    #
    # Out Of Sync Applications
    #
    - record: argocd:applications:out_of_sync
      expr: |
        count(
          argocd_app_info{
            sync_status!="Synced"
          }
        )


    #
    # Healthy Applications
    #
    - record: argocd:applications:healthy
      expr: |
        count(
          argocd_app_info{
            health_status="Healthy"
          }
        )


    #
    # Degraded Applications
    #
    - record: argocd:applications:degraded
      expr: |
        count(
          argocd_app_info{
            health_status="Degraded"
          }
        )


    #
    # Failed Sync Operations
    #
    - record: argocd:sync_failures_total
      expr: |
        sum(
          rate(
            argocd_app_sync_total{
              phase="Failed"
            }[5m]
          )
        )


    #
    # Application Reconciliation Rate
    #
    - record: argocd:app_reconcile_rate
      expr: |
        sum(
          rate(
            argocd_app_reconcile_count[5m]
          )
        )