---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: prometheus
spec:
  encryptedData:
    admin-password: AgAQyQ66Ysut6JmTwwXDcwgboeFZZSlt55wNBCXT644naqFNIHHXFbYl/ZZoGDRj1YvQUSnbA5RWe2jGKwne6i9yO6QOy2wm36NnIlj42orQi+5OiAQgRJ4uEXkExnzE934VunxBr9+DTAH27AQpSVSkBBH7oBkCa5sYHvii1devvPzgI7wIB9X5DJ8Fc853YIr2iW95KQYDo1djS7eifFsROHMWQbeKDAXZNHcl4PLrQG7EtMegcW0PlYzh931C8Pw0YzeLeO9EHcT83rfXrNtKwwRFiH6vObWjJ3oJ7jwIL4R1SgC658fu91oMz4h5Zo7oGTOiR1UitFcf98WZwQWOzGBF32kcnXf5cSH2ivkq/pG8lEXNNiB4W6Hlhl4uVVa4YYSWqJt8oSTHj2jpzuNwTd6dLvHTUq7G+x/xyTbEfCU//hIJC7Hlkl4SONy8yq6sHnlVyY3Q9VPOsGMlBu/YO13YGKXgmfoHifzE1Z6rCo3AbBWIrrRekE4BqMYOfRhMdWOfQQZPeIUgUU42DnegUFvIHlJC2XSZyS+fDFc1je5HZgW+JvWqb/ZZhvjkPTZE3uFdQuVkKOpK8c09zTId4rZ33R9VoIYqX5XGeLe1a8N/UJbAEP0d8JdsgKuwHWf0BOjNlTLm1sviMqReIQoa/pGap3cjDRatN6J5cMrc37+SSHBj5RpIrrX4/X9dhVMM8Xwqa705BA==
    admin-user: AgCUtvoYk9ViC9gC4YwIPxhK7lY84D3fx4hEahG+P0Wdv6RAey6jbHLQRTXrqECKbV66DuDOYJmcOG9zMDg3sS2aGTPb1A3Q5jQIip/RikA40u04yG3QIseI3nw3A92xTwSgFzO7lRXM2MaYY07X3+0bg3hh1aixTeULSQ6+vfh2hZvbjCI/a0TvDBTONL98KRAP1wU5kUa0rrpH+lknlxDikEWV83FwAW3FoHE5jS3KWDMYTBgsFVZGQJXGmS4zKpyKCRDu/SGm7F+qW+PWMeIH2QSlI+cOOmpuScpa82oQgO5gNI40IUjEInRkgguhr1I9EA8iGHzVTHtSjdkFU3uJ7ilz8NUg86u41Gdq4UQiH55ShADeMEmWYr4xDhY2ELHhtyfhX3HLx/LT6n25nwxGbGMvXbU9745YxvC02VFan4o8+/i0p/n8xvpKj2H2oWvEteeCrEDtvzVRYB/+PFS0gxyATxXbK63kex4d0ibwzmOl0LcbzqZIcFzkBYzRBX2XnbAAdkHw+owBcCz4Y68Pl8TsbMVNICCfo0kyCguy+EjDRo+mNz28znRZDGmQuHWVFMS4py2GWq2LB1w3sQWcA7rW3gSV/ak8fFPVBhtdLLKxOSzswxCuCombiHeJVdQ07USVBpU/TEFIkiRHI16HMWXK91+GFaLSO7TvEWRHeL2yhuA1Hf+Nx9VVvivtrmNw6z8oUQ==
  template:
    metadata:
      name: grafana-admin
      namespace: prometheus
    type: Opaque
