#  Authentication 
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-secretsmanager
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets

---
# Fetch Secrets
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin
  namespace: prometheus
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: grafana-admin          # must match exactly what kube-prom-stack.yaml expects
    creationPolicy: Owner
  data:
    - secretKey: admin-user
      remoteRef:
        key: online-boutique/grafana-admin
        property: admin-user
    - secretKey: admin-password
      remoteRef:
        key: online-boutique/grafana-admin
        property: admin-password
