apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  sources:
    - chart: alloy
      repoURL: https://grafana.github.io/helm-charts
      targetRevision: 1.10.1
      helm:
        valueFiles:
          - $values/clusters/boutique/platform-configs/helm-values/alloy.yaml

    - repoURL: https://github.com/susu10-10/online-boutique-doks-pf
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: alloy

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true