apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: certificates
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/susu10-10/online-boutique-doks-pf'
    targetRevision: main
    path: clusters/boutique/platform-configs/cert-manager
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: true