apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd # Must match the namespace where Argo CD is installed
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io # Enables cascading delete
spec:
  project: default
  sources:
    - repoURL: 'https://charts.jetstack.io' # Helm registry URL
      chart: cert-manager   # Chart name
      targetRevision: 1.21.0      # Version of the chart
      helm:
        valueFiles:
        - $values/clusters/boutique/platform-configs/helm-values/cert-manager.yaml
    - repoURL: 'https://github.com/susu10-10/online-boutique-eks-pf'
      targetRevision: main
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'    # Target cluster
    namespace: cert-manager                    # Target namespace
  syncPolicy:
    automated:
      prune: false                           # Automatically delete removed resources
      selfHeal: true                            # Fix configuration drift automatically
    syncOptions:
      - CreateNamespace=true                     # Automatically create target namespace
