apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"

spec:
  project: default

  source:
    repoURL: https://github.com/susu10-10/online-boutique-eks-pf
    targetRevision: main
    path: clusters/boutique/platform-configs/secrets

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true