apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-rules
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"

spec:
  project: default

  sources:
    - repoURL: https://github.com/susu10-10/online-boutique-eks-pf
      targetRevision: main
      path: clusters/boutique/platform-configs/monitoring/recording-rules
    - repoURL: https://github.com/susu10-10/online-boutique-eks-pf
      targetRevision: main
      path: clusters/boutique/platform-configs/monitoring/alerting-rules

  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus

  syncPolicy:
    automated:
      prune: true
      selfHeal: true