apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default

  sources:
    - repoURL: 'https://bitnami.github.io/sealed-secrets'
      chart: sealed-secrets
      targetRevision: 2.19.1
      helm:
        valuesFiles:
          - $values/clusters/boutique/platform-configs/helm-values/sealed-secrets.yaml 
    - repoURL: 'https://github.com/susu10-10/online-boutique-doks-pf'
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true