apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: monitoring-servicemonitors
  namespace: argocd

spec:

  project: default

  source:
    repoURL: https://github.com/susu10-10/online-boutique-doks-pf
    targetRevision: main
    path: clusters/boutique/platform-configs/monitoring/servicemonitors

  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus

  syncPolicy:
    automated:
      prune: true
      selfHeal: true