apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trust-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"   # after cert-manager (wave 0), before certificates (wave 2)
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: 'https://charts.jetstack.io'
      chart: trust-manager
      targetRevision: 0.13.0
      helm:
        parameters:
          - name: app.trust.namespace
            value: linkerd
    - repoURL: 'https://github.com/susu10-10/online-boutique-eks-pf'
      targetRevision: main
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager   # trust-manager installs alongside cert-manager
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
